; ========================================
; dnstun SERVER configuration
; ========================================

[core]
server_bind              = 0.0.0.0:53
workers                  = 4
threads                  = 2
log_level                = info        ; silent | info | debug

[tuning]
idle_timeout_sec         = 120

[domains]
list                     = tun.example.com

[encryption]
enabled                  = false
cipher                   = chacha20    ; chacha20 | aes256gcm | noise_nk
psk                      = changeme    ; pre-shared key (must match client)
; privkey_file           = server.key  ; Noise_NK private key

[swarm]
serve                    = true        ; send resolver list to clients on SYNC
save_to_disk             = true        ; write swarm.txt periodically
